# Workflow Rules for Drift Project
# Validation rules for workflow patterns in commands and skills

group_name: "Workflow Patterns"

# ==============================================================================
# CREATE ISSUE WORKFLOW
# ==============================================================================
create_issue_workflow:
  description: "Validate create-issue command workflow patterns"
  scope: project_level
  context: "Issue creation workflow must use proper integration and require user approval"
  requires_project_context: true
  supported_clients:
    - claude-code
  document_bundle:
    bundle_type: command
    file_patterns:
      - .claude/commands/create-issue.md
    bundle_strategy: individual
  phases:
    - name: check_approval_checkpoint
      type: prompt
      prompt: |
        Check if the workflow requires user approval before creating GitHub issues.

        CRITICAL ISSUES (report these):
        1. No mention of user approval requirement before creating issues
        2. Instructs to create issues without user review/approval

        ACCEPTABLE (do NOT report):
        - Any language requiring user approval or review before creating
        - Presents draft to user for review
        - Waits for user confirmation

    - name: check_integration_method
      type: prompt
      prompt: |
        Check if the workflow uses appropriate GitHub integration tools.

        CRITICAL ISSUES (report these):
        1. No mention of how to integrate with GitHub for issue creation
        2. Uses deprecated or inappropriate integration methods

        ACCEPTABLE (do NOT report):
        - Documents use of MCP tools, API, or other integration methods
        - Provides guidance on GitHub integration

# ==============================================================================
# CREATE PR WORKFLOW
# ==============================================================================
create_pr_workflow:
  description: "Validate create-pr command workflow patterns"
  scope: project_level
  context: "PR creation must have quality validation and require user approval"
  requires_project_context: true
  supported_clients:
    - claude-code
  document_bundle:
    bundle_type: command
    file_patterns:
      - .claude/commands/create-pr.md
    bundle_strategy: individual
  phases:
    - name: check_quality_gates
      type: prompt
      prompt: |
        Check if the workflow includes quality validation before PR creation.

        CRITICAL ISSUES (report these):
        1. No mention of any quality validation (testing, linting, checking)
        2. Creates PR without any validation steps

        ACCEPTABLE (do NOT report):
        - Mentions running tests, linters, or any quality checks
        - References validation scripts or tools
        - Requires quality validation before PR

    - name: check_approval_checkpoint
      type: prompt
      prompt: |
        Check if the workflow requires user approval before creating PR.

        CRITICAL ISSUES (report these):
        1. No mention of user approval requirement before creating PR
        2. Instructs to create PR without user review/approval

        ACCEPTABLE (do NOT report):
        - Any language requiring user approval or review before creating
        - Presents draft to user for review
        - Waits for user confirmation

# ==============================================================================
# WORK ON ISSUE WORKFLOW
# ==============================================================================
work_on_issue_workflow:
  description: "Validate work-on-issue command workflow patterns"
  scope: project_level
  context: "Issue implementation should delegate to specialized agents and validate quality"
  requires_project_context: true
  supported_clients:
    - claude-code
  document_bundle:
    bundle_type: command
    file_patterns:
      - .claude/commands/work-on-issue.md
    bundle_strategy: individual
  phases:
    - name: check_delegation_pattern
      type: prompt
      prompt: |
        Check if the workflow delegates to specialized agents rather than doing everything directly.

        CRITICAL ISSUES (report these):
        1. No mention of delegating to specialized agents/tools
        2. Instructs to do all implementation, testing, and documentation directly

        ACCEPTABLE (do NOT report):
        - Delegates implementation to developer agent/tool
        - Delegates testing to qa agent/tool
        - Uses specialized agents for different aspects
        - Mentions delegation or using Task tool

    - name: check_quality_validation
      type: prompt
      prompt: |
        Check if the workflow includes quality validation.

        CRITICAL ISSUES (report these):
        1. No mention of any quality validation steps
        2. Skips testing and code quality checks

        ACCEPTABLE (do NOT report):
        - Mentions running quality checks, tests, or linters
        - References validation before completion

# ==============================================================================
# FULL CHECK WORKFLOW
# ==============================================================================
full_check_workflow:
  description: "Validate full-check command includes comprehensive quality validation"
  scope: project_level
  context: "Full validation should include multiple quality checks"
  requires_project_context: true
  supported_clients:
    - claude-code
  document_bundle:
    bundle_type: command
    file_patterns:
      - .claude/commands/full-check.md
    bundle_strategy: individual
  phases:
    - name: check_comprehensive_validation
      type: prompt
      prompt: |
        Check if the workflow runs comprehensive quality validation.

        CRITICAL ISSUES (report these):
        1. Only runs one type of validation (only tests OR only linting)
        2. Missing comprehensive validation

        ACCEPTABLE (do NOT report):
        - Runs multiple types of quality checks
        - Mentions both testing and code quality validation
        - Comprehensive or full validation mentioned

# ==============================================================================
# GITHUB OPERATIONS SKILL
# ==============================================================================
github_operations_skill:
  description: "Validate GitHub operations skill patterns"
  scope: project_level
  context: "GitHub operations should use proper integration methods"
  requires_project_context: true
  supported_clients:
    - claude-code
  document_bundle:
    bundle_type: skill
    file_patterns:
      - .claude/skills/github-operations/SKILL.md
    bundle_strategy: individual
  phases:
    - name: check_integration_guidance
      type: prompt
      prompt: |
        Check if skill provides guidance on GitHub integration.

        CRITICAL ISSUES (report these):
        1. No mention of how to integrate with GitHub
        2. Missing guidance on repository information handling

        ACCEPTABLE (do NOT report):
        - Provides integration method documentation
        - Mentions determining repository information
        - Documents GitHub integration tools/APIs

# ==============================================================================
# TESTING SKILL
# ==============================================================================
testing_skill:
  description: "Validate testing skill patterns"
  scope: project_level
  context: "Testing should require adequate coverage"
  requires_project_context: true
  supported_clients:
    - claude-code
  document_bundle:
    bundle_type: skill
    file_patterns:
      - .claude/skills/testing/SKILL.md
    bundle_strategy: individual
  phases:
    - name: check_coverage_guidance
      type: prompt
      prompt: |
        Check if skill provides test coverage guidance.

        CRITICAL ISSUES (report these):
        1. No mention of test coverage expectations or requirements
        2. Missing testing standards

        ACCEPTABLE (do NOT report):
        - Mentions coverage requirements or targets
        - Provides testing standards
        - Documents coverage expectations

# ==============================================================================
# LINTING SKILL
# ==============================================================================
linting_skill:
  description: "Validate linting skill patterns"
  scope: project_level
  context: "Linting should enforce code quality standards"
  requires_project_context: true
  supported_clients:
    - claude-code
  document_bundle:
    bundle_type: skill
    file_patterns:
      - .claude/skills/linting/SKILL.md
    bundle_strategy: individual
  phases:
    - name: check_quality_standards
      type: prompt
      prompt: |
        Check if skill defines code quality standards.

        CRITICAL ISSUES (report these):
        1. No mention of code quality standards or linting tools
        2. Missing quality enforcement guidance

        ACCEPTABLE (do NOT report):
        - Mentions linting tools or code quality checks
        - Defines quality standards
        - Documents linting process
