# Drift Configuration for drift project
# This file defines custom rule definitions specific to this project

providers:
  bedrock:
    provider: bedrock
    params:
      region: us-east-1

models:
  haiku:
    provider: bedrock
    model_id: us.anthropic.claude-haiku-4-5-20251001-v1:0
  sonnet:
    provider: bedrock
    model_id: us.anthropic.claude-sonnet-4-5-20250929-v1:0

default_model: haiku

agent_tools:
  claude-code:
    conversation_path: ~/.claude/projects/
    enabled: true

conversations:
  mode: latest
  days: 7

temp_dir: /tmp/drift

rule_definitions:
  # All rules are project-level focused on documentation quality
  skill_completeness:
    description: "Claude Code skills missing essential components or clarity"
    scope: project_level
    context: "Incomplete skills create confusion and slow development. Skills must be self-contained with clear examples and dependencies."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: skill
      file_patterns:
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
      resource_patterns:
        - "**/*.py"
        - "**/*.js"
        - "**/*.md"
        - "**/*.ts"
    phases:
      - name: basic_structure
        type: prompt
        model: sonnet
        prompt: |
          Check if the skill has basic structure: clear title, purpose, examples.
          Look for obvious missing components or vague instructions.

          Focus on:
          - References to external files that don't exist in the skill bundle
          - Missing practical examples or walkthroughs demonstrating usage
          - Broken or dangling references to resources

          Do NOT flag:
          - Missing MCP function call syntax explanations - AI can figure this out
          - Missing explicit "activation criteria" sections - description is enough
          - Missing "when NOT to use" sections - optional nice-to-have

          CONSOLIDATION: If multiple skills have the same type of issue, consolidate them.
          Return ONE finding that lists all affected skills, not separate findings per skill.
        available_resources:
          - skill
      - name: verify_dependencies
        type: prompt
        model: sonnet
        prompt: |
          If the skill references other skills, verify they exist by requesting them.
          Only flag missing references to actual files/resources, not missing metadata sections.

          CONSOLIDATION: If multiple skills have missing dependencies, consolidate into one finding.
        available_resources:
          - skill
      - name: final_quality_check
        type: prompt
        model: sonnet
        prompt: |
          Review all findings from previous phases and make final determination.

          CRITICAL: Return EXACTLY ONE finding that represents the MOST IMPORTANT issue.
          If multiple skills have similar issues, consolidate them into one finding.

          Format your response as a JSON array with ONE element:
          [{"observed_issue": "...", "expected_quality": "...", "file_paths": [...], "context": "..."}]

          If no issues found, return empty array: []
        available_resources:
          - skill

  agent_completeness:
    description: "Claude Code agents missing essential components or clarity"
    scope: project_level
    context: "Incomplete agents create confusion about delegation and task automation. Agents must clearly define their scope and dependencies."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: agent
      file_patterns:
        - .claude/agents/*.md
      bundle_strategy: individual
      resource_patterns: []
    phases:
      - name: basic_structure
        type: prompt
        model: sonnet
        prompt: |
          Check if the agent has basic structure: clear purpose, tool declarations, examples.
          Look for obvious missing components or vague task descriptions.

          Focus on structural gaps like:
          - Missing workflow guidance (how to approach tasks systematically)
          - Missing decision criteria for choosing between strategies
          - Unexplained custom tools or dependencies that aren't standard

          Do NOT flag:
          - References to standard project scripts (./lint.sh, ./test.sh) - assume they exist
          - Lack of detailed MCP tool parameter documentation - AI can figure this out

          CONSOLIDATION: If multiple agents have the same issue, consolidate into one finding.
        available_resources:
          - agent
      - name: verify_references
        type: prompt
        model: sonnet
        prompt: |
          If the agent references other agents or skills, verify they exist by requesting them.

          CONSOLIDATION: If multiple agents have missing references, consolidate into one finding.
        available_resources:
          - agent
          - skill
      - name: final_quality_check
        type: prompt
        model: sonnet
        prompt: |
          Review all findings from previous phases and make final determination.

          CRITICAL: Return EXACTLY ONE finding that represents the MOST IMPORTANT issue.
          If multiple agents have similar issues, consolidate them into one finding.

          Format your response as a JSON array with ONE element:
          [{"observed_issue": "...", "expected_quality": "...", "file_paths": [...], "context": "..."}]

          If no issues found, return empty array: []
        available_resources:
          - agent
          - skill

  command_completeness:
    description: "Claude Code commands missing essential components or clarity"
    scope: project_level
    context: "Incomplete commands miss validation steps and create workflow inefficiency. Commands must declare dependencies and provide clear execution steps."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: command
      file_patterns:
        - .claude/commands/*.md
      bundle_strategy: individual
      resource_patterns: []
    phases:
      - name: basic_structure
        type: prompt
        model: sonnet
        prompt: |
          Check if the command has basic structure: clear purpose, execution steps, examples.

          Focus on:
          - Missing step-by-step execution workflow
          - Missing error handling guidance or prerequisites
          - Unclear command parameters or invocation

          Do NOT flag:
          - Missing detailed MCP tool parameter docs - AI can infer these
          - Missing example output formats - nice-to-have, not required
          - Missing explanation of obvious variables like $ARGUMENTS
          - Missing "Required skills:" section - optional metadata

          CONSOLIDATION: If multiple commands have the same issue, consolidate into one finding.
        available_resources:
          - command
          - skill
          - agent
      - name: verify_dependencies
        type: prompt
        model: sonnet
        prompt: |
          If the command references other commands, skills, or agents, verify they exist.
          Request command, skill, or agent resources as needed.

          CONSOLIDATION: If multiple commands have missing dependencies, consolidate into one finding.
        available_resources:
          - command
          - skill
          - agent
      - name: final_quality_check
        type: prompt
        model: sonnet
        prompt: |
          Review all findings from previous phases and make final determination.

          CRITICAL: Return EXACTLY ONE finding that represents the MOST IMPORTANT issue.
          If multiple commands have similar issues, consolidate them into one finding.

          Format your response as a JSON array with ONE element:
          [{"observed_issue": "...", "expected_quality": "...", "file_paths": [...], "context": "..."}]

          If no issues found, return empty array: []
        available_resources:
          - command
          - skill
          - agent

  command_consistency:
    description: "Commands contradict project guidelines or each other"
    scope: project_level
    context: "Contradictory commands create confusion and workflow inefficiency. Commands must be consistent with project guidelines and declare their dependencies."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: mixed
      file_patterns:
        - .claude/commands/*.md
        - CLAUDE.md
      bundle_strategy: collection
      resource_patterns: []
    phases:
      - name: detection
        type: prompt
        model: haiku
        prompt: |
          Analyze these command documents for consistency and contradictions.

          Project root: {project_root}

          Files being analyzed:
          {files_with_paths}

          Focus on these patterns:
          - Commands that contradict CLAUDE.md guidelines
          - Inconsistent parameter naming across commands
          - Conflicting approaches to similar tasks
          - Different terminology for the same concepts

          When reporting, cite specific files and conflicting content.

          CONSOLIDATION: If you find multiple contradictions, consolidate them into ONE finding.
          List all affected files in the file_paths array.

          CRITICAL: Return EXACTLY ONE finding total for this rule.
          If multiple contradictions exist, pick the MOST IMPORTANT one and report only that.

          Format your response as a JSON array with ONE element:
          [{"observed_issue": "...", "expected_quality": "...", "file_paths": [...], "context": "..."}]

          Example contradictions:
          - Command A says "always run tests first" but Command B runs lint first
          - One command uses --force flag, another uses --skip-checks for same purpose
          - CLAUDE.md says use skill X, but command implements custom solution

          If no contradictions found, return empty array: []
        available_resources: []

  claude_md_missing:
    description: "Project missing CLAUDE.md configuration file"
    scope: project_level
    context: "CLAUDE.md provides essential context for Claude Code about project structure and conventions. Missing this file reduces AI effectiveness."
    requires_project_context: true
    supported_clients:
      - claude-code
    phases:
      - name: check_file
        type: file_exists
        file_path: CLAUDE.md
        failure_message: "CLAUDE.md file is missing from project root"
        expected_behavior: "Project should have CLAUDE.md file documenting structure and conventions"

  command_duplicate_dependencies:
    description: "Commands have redundant transitive skill dependencies"
    scope: project_level
    context: "Commands should only declare direct skill dependencies. Transitive dependencies are automatically included."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: mixed
      file_patterns:
        - .claude/commands/*.md
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_duplicates
        type: dependency_duplicate
        description: "Check for redundant transitive dependencies in commands"
        failure_message: "Found redundant skill dependencies in commands"
        expected_behavior: "Commands should only declare direct dependencies, not transitive ones"
        params:
          resource_dirs:
            - .claude/commands
            - .claude/skills

  skill_duplicate_dependencies:
    description: "Skills have redundant transitive skill dependencies"
    scope: project_level
    context: "Skills should only declare direct dependencies on other skills. Transitive dependencies are automatically included."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: skill
      file_patterns:
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_duplicates
        type: dependency_duplicate
        description: "Check for redundant transitive dependencies in skills"
        failure_message: "Found redundant skill dependencies in skills"
        expected_behavior: "Skills should only declare direct dependencies, not transitive ones"
        params:
          resource_dirs:
            - .claude/skills

  agent_duplicate_dependencies:
    description: "Agents have redundant transitive skill dependencies"
    scope: project_level
    context: "Agents should only declare direct skill dependencies. Transitive dependencies are automatically included."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: agent
      file_patterns:
        - .claude/agents/*.md
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_duplicates
        type: dependency_duplicate
        description: "Check for redundant transitive dependencies in agents"
        failure_message: "Found redundant skill dependencies in agents"
        expected_behavior: "Agents should only declare direct dependencies, not transitive ones"
        params:
          resource_dirs:
            - .claude/agents
            - .claude/skills

  command_broken_links:
    description: "Commands contain broken file references or links"
    scope: project_level
    context: "Commands must reference valid files and resources. Broken links cause confusion and errors."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: command
      file_patterns:
        - .claude/commands/*.md
      bundle_strategy: individual
    phases:
      - name: check_links
        type: markdown_link
        description: "Check for broken links in command documentation"
        failure_message: "Found broken links in commands"
        expected_behavior: "All file references and links should be valid"
        params:
          check_local_files: true
          check_external_urls: false

  skill_broken_links:
    description: "Skills contain broken file references or links"
    scope: project_level
    context: "Skills must reference valid files and resources. Broken links cause confusion and errors."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: skill
      file_patterns:
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_links
        type: markdown_link
        description: "Check for broken links in skill documentation"
        failure_message: "Found broken links in skills"
        expected_behavior: "All file references and links should be valid"
        params:
          check_local_files: true
          check_external_urls: false

  agent_broken_links:
    description: "Agents contain broken file references or links"
    scope: project_level
    context: "Agents must reference valid files and resources. Broken links cause confusion and errors."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: agent
      file_patterns:
        - .claude/agents/*.md
      bundle_strategy: individual
    phases:
      - name: check_links
        type: markdown_link
        description: "Check for broken links in agent documentation"
        failure_message: "Found broken links in agents"
        expected_behavior: "All file references and links should be valid"
        params:
          check_local_files: true
          check_external_urls: false
