# Drift Configuration for drift project
# This file defines custom rule definitions specific to this project

providers:
  bedrock:
    provider: bedrock
    params:
      region: us-east-1

models:
  haiku:
    provider: bedrock
    model_id: us.anthropic.claude-haiku-4-5-20251001-v1:0
  sonnet:
    provider: bedrock
    model_id: us.anthropic.claude-sonnet-4-5-20250929-v1:0

default_model: haiku

agent_tools:
  claude-code:
    conversation_path: ~/.claude/projects/
    enabled: true

conversations:
  mode: latest
  days: 7

temp_dir: /tmp/drift

rule_definitions:
  # All rules are project-level focused on documentation quality
  skill_completeness:
    description: "Claude Code skills missing essential components or clarity"
    scope: project_level
    context: "Incomplete skills create confusion and slow development. Skills must be self-contained with clear examples and dependencies."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: skill
      file_patterns:
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
      resource_patterns:
        - "**/*.py"
        - "**/*.js"
        - "**/*.md"
        - "**/*.ts"
    phases:
      - name: structural_quality
        type: prompt
        model: sonnet
        prompt: |
          Evaluate the skill's structural quality per Anthropic's Agent Skills best practices.

          CRITICAL ISSUES (report these):
          1. Frontmatter description COMPLETELY MISSING "when to use" or "use when" phrase
          2. Multi-page templates or large reference content dumped inline (>100 lines of template/boilerplate)
          3. Entire skill is just vague responsibilities with NO actionable instructions anywhere

          ACCEPTABLE (do NOT report):
          - Any "Use when..." phrase in frontmatter, even if brief (e.g., "Use when writing tests" is FINE)
          - Skills that start with brief intro then dive into instructions
          - "Core Responsibilities" sections IF followed by actionable content
          - References to project files/scripts (assume they exist)
          - Missing examples IF the skill content is self-explanatory

          EXAMPLES OF WHAT TO IGNORE:
          - "Use when writing or structuring issues" ✓ ACCEPTABLE
          - "Use when fixing linting errors" ✓ ACCEPTABLE
          - "Expert in X" then actionable content ✓ ACCEPTABLE

          ONLY REPORT if there's a REAL structural problem, not style nitpicks.
        available_resources:
          - skill
      - name: verify_dependencies
        type: prompt
        model: sonnet
        prompt: |
          If the skill references other skills, verify they exist by requesting them.
          Only flag missing references to actual dependency skills.
        available_resources:
          - skill
      - name: final_quality_check
        type: prompt
        model: sonnet
        prompt: |
          Review all findings from previous phases.

          ONLY report CRITICAL structural problems:
          - Missing "use when" activation criteria entirely
          - Massive content dumps (templates >100 lines inline)
          - No actionable instructions anywhere

          IGNORE minor style issues:
          - Slight wording variations in "use when" phrases
          - Brief introductory sections
          - "Core Responsibilities" if actionable content follows
        available_resources:
          - skill

  agent_completeness:
    description: "Claude Code agents missing essential components or clarity"
    scope: project_level
    context: "Incomplete agents create confusion about delegation and task automation. Agents must clearly define their scope and dependencies."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: agent
      file_patterns:
        - .claude/agents/*.md
      bundle_strategy: individual
      resource_patterns: []
    phases:
      - name: workflow_quality
        type: prompt
        model: sonnet
        prompt: |
          Evaluate the agent's workflow guidance and task delegation clarity.

          CRITICAL ISSUES (report these):
          - Agent has NO purpose or scope explanation anywhere
          - Agent provides ZERO workflow guidance (doesn't explain how to approach tasks at all)
          - Agent is completely missing examples

          ACCEPTABLE (do NOT report):
          - References to MCP tools without explaining setup
          - Brief or general workflow descriptions (some guidance is better than none)
          - Agent lists responsibilities without exhaustive decision criteria
          - References to standard project scripts/tools

          ONLY REPORT if there's a REAL problem, not style nitpicks.
        available_resources:
          - agent
      - name: verify_references
        type: prompt
        model: sonnet
        prompt: |
          If the agent references other agents or skills, verify they exist by requesting them.
          Only flag missing references to actual dependency agents or skills.
        available_resources:
          - agent
          - skill
      - name: final_quality_check
        type: prompt
        model: sonnet
        prompt: |
          Review all findings from previous phases.

          ONLY report CRITICAL problems:
          - Missing workflow guidance entirely
          - No purpose/scope explanation at all
          - Completely missing examples

          IGNORE minor issues and style preferences.
        available_resources:
          - agent
          - skill

  command_completeness:
    description: "Claude Code commands missing essential components or clarity"
    scope: project_level
    context: "Incomplete commands miss validation steps and create workflow inefficiency. Commands must declare dependencies and provide clear execution steps."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: command
      file_patterns:
        - .claude/commands/*.md
      bundle_strategy: individual
      resource_patterns: []
    phases:
      - name: execution_clarity
        type: prompt
        model: sonnet
        prompt: |
          Evaluate the command's execution clarity and usability.

          CRITICAL ISSUES (report these):
          - Command has NO purpose explanation anywhere
          - Command provides ZERO execution guidance (no steps at all)
          - Invocation syntax completely missing or totally unclear

          ACCEPTABLE (do NOT report):
          - References to project scripts (./test.sh, ./lint.sh)
          - References to MCP tools by name
          - Parameter placeholders like <issue_number>, $ARGUMENTS
          - Brief execution steps (some guidance is better than none)
          - Missing exhaustive success criteria (nice-to-have)

          ONLY REPORT if there's a REAL problem, not style nitpicks.
        available_resources:
          - command
          - skill
          - agent
      - name: verify_dependencies
        type: prompt
        model: sonnet
        prompt: |
          If the command references other commands, skills, or agents, verify they exist.
          Only flag missing references to actual dependencies.
        available_resources:
          - command
          - skill
          - agent
      - name: final_quality_check
        type: prompt
        model: sonnet
        prompt: |
          Review all findings from previous phases.

          ONLY report CRITICAL problems:
          - Missing purpose entirely
          - Zero execution guidance
          - Completely unclear invocation

          IGNORE minor issues and style preferences.
        available_resources:
          - command
          - skill
          - agent

  command_consistency:
    description: "Commands contradict project guidelines or each other"
    scope: project_level
    context: "Contradictory commands create confusion and workflow inefficiency. Commands must be consistent with project guidelines and declare their dependencies."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: mixed
      file_patterns:
        - .claude/commands/*.md
        - CLAUDE.md
      bundle_strategy: collection
      resource_patterns: []
    phases:
      - name: consistency_check
        type: prompt
        model: haiku
        prompt: |
          Analyze commands for consistency and contradictions.

          Project root: {project_root}
          Files: {files_with_paths}

          CRITICAL ISSUES (report these):
          - Commands give contradictory guidance (Command A says X, Command B says opposite)
          - Commands contradict CLAUDE.md guidelines
          - Major inconsistencies that would confuse users

          ACCEPTABLE (do NOT report):
          - Minor wording variations
          - Different approaches to different problems
          - Redundant information (context efficiency is nice-to-have)
        available_resources: []

  claude_md_missing:
    description: "Project missing CLAUDE.md configuration file"
    scope: project_level
    context: "CLAUDE.md provides essential context for Claude Code about project structure and conventions. Missing this file reduces AI effectiveness."
    requires_project_context: true
    supported_clients:
      - claude-code
    phases:
      - name: check_file
        type: file_exists
        file_path: CLAUDE.md
        failure_message: "CLAUDE.md file is missing from project root"
        expected_behavior: "Project should have CLAUDE.md file documenting structure and conventions"

  command_duplicate_dependencies:
    description: "Commands have redundant transitive skill dependencies"
    scope: project_level
    context: "Commands should only declare direct skill dependencies. Transitive dependencies are automatically included."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: mixed
      file_patterns:
        - .claude/commands/*.md
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_duplicates
        type: dependency_duplicate
        description: "Check for redundant transitive dependencies in commands"
        failure_message: "Found redundant skill dependencies in commands"
        expected_behavior: "Commands should only declare direct dependencies, not transitive ones"
        params:
          resource_dirs:
            - .claude/commands
            - .claude/skills

  skill_duplicate_dependencies:
    description: "Skills have redundant transitive skill dependencies"
    scope: project_level
    context: "Skills should only declare direct dependencies on other skills. Transitive dependencies are automatically included."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: skill
      file_patterns:
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_duplicates
        type: dependency_duplicate
        description: "Check for redundant transitive dependencies in skills"
        failure_message: "Found redundant skill dependencies in skills"
        expected_behavior: "Skills should only declare direct dependencies, not transitive ones"
        params:
          resource_dirs:
            - .claude/skills

  agent_duplicate_dependencies:
    description: "Agents have redundant transitive skill dependencies"
    scope: project_level
    context: "Agents should only declare direct skill dependencies. Transitive dependencies are automatically included."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: agent
      file_patterns:
        - .claude/agents/*.md
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_duplicates
        type: dependency_duplicate
        description: "Check for redundant transitive dependencies in agents"
        failure_message: "Found redundant skill dependencies in agents"
        expected_behavior: "Agents should only declare direct dependencies, not transitive ones"
        params:
          resource_dirs:
            - .claude/agents
            - .claude/skills

  command_broken_links:
    description: "Commands contain broken file references or links"
    scope: project_level
    context: "Commands must reference valid files and resources. Broken links cause confusion and errors."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: command
      file_patterns:
        - .claude/commands/*.md
      bundle_strategy: individual
    phases:
      - name: check_links
        type: markdown_link
        description: "Check for broken links in command documentation"
        failure_message: "Found broken links in commands"
        expected_behavior: "All file references and links should be valid"
        params:
          check_local_files: true
          check_external_urls: false
          # Skip common example/placeholder file patterns in documentation
          custom_skip_patterns:
            - '\.py'               # Python files in examples (test_parser.py, cli.py, etc.)
            - '\.yaml'             # YAML config files (config.yaml, drift.yaml, pre-commit-config.yaml, etc.)
            - '\.yml'              # YAML workflow files (test.yml, release.yml, etc.)
            - '\.cfg'              # Config files (setup.cfg, etc.)
            - 'CHANGELOG\.md'      # Changelog references in examples
            - 'github/workflows/'  # GitHub workflow directory references

  skill_broken_links:
    description: "Skills contain broken file references or links"
    scope: project_level
    context: "Skills must reference valid files and resources. Broken links cause confusion and errors."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: skill
      file_patterns:
        - .claude/skills/*/SKILL.md
      bundle_strategy: individual
    phases:
      - name: check_links
        type: markdown_link
        description: "Check for broken links in skill documentation"
        failure_message: "Found broken links in skills"
        expected_behavior: "All file references and links should be valid"
        params:
          check_local_files: true
          check_external_urls: false
          # Skip common example/placeholder file patterns in documentation
          custom_skip_patterns:
            - '\.py'               # Python files in examples (test_parser.py, cli.py, etc.)
            - '\.yaml'             # YAML config files (config.yaml, drift.yaml, pre-commit-config.yaml, etc.)
            - '\.yml'              # YAML workflow files (test.yml, release.yml, etc.)
            - '\.cfg'              # Config files (setup.cfg, etc.)
            - 'CHANGELOG\.md'      # Changelog references in examples
            - 'github/workflows/'  # GitHub workflow directory references

  agent_broken_links:
    description: "Agents contain broken file references or links"
    scope: project_level
    context: "Agents must reference valid files and resources. Broken links cause confusion and errors."
    requires_project_context: true
    supported_clients:
      - claude-code
    document_bundle:
      bundle_type: agent
      file_patterns:
        - .claude/agents/*.md
      bundle_strategy: individual
    phases:
      - name: check_links
        type: markdown_link
        description: "Check for broken links in agent documentation"
        failure_message: "Found broken links in agents"
        expected_behavior: "All file references and links should be valid"
        params:
          check_local_files: true
          check_external_urls: false
          # Skip common example/placeholder file patterns in documentation
          custom_skip_patterns:
            - '\.py'               # Python files in examples (test_parser.py, cli.py, etc.)
            - '\.yaml'             # YAML config files (config.yaml, drift.yaml, pre-commit-config.yaml, etc.)
            - '\.yml'              # YAML workflow files (test.yml, release.yml, etc.)
            - '\.cfg'              # Config files (setup.cfg, etc.)
            - 'CHANGELOG\.md'      # Changelog references in examples
            - 'github/workflows/'  # GitHub workflow directory references

  claude_skill_permissions:
    description: "Project skills missing from Claude Code settings permissions"
    scope: project_level
    context: "All skills in .claude/skills/ must have corresponding Skill() permission entries in .claude/settings.json. Missing permissions prevent skills from being used."
    requires_project_context: true
    supported_clients:
      - claude-code
    phases:
      - name: check_skill_permissions
        type: claude_skill_settings
        failure_message: "Skills missing from .claude/settings.json permissions.allow array"
        expected_behavior: "Every skill directory in .claude/skills/ should have a corresponding Skill(name) entry in .claude/settings.json"

  claude_settings_duplicates:
    description: "Duplicate permission entries in Claude Code settings"
    scope: project_level
    context: "The .claude/settings.json permissions.allow array should not contain duplicate entries. Duplicates are unnecessary and can cause confusion."
    requires_project_context: true
    phases:
      - name: check_duplicate_permissions
        type: claude_settings_duplicates
        failure_message: "Duplicate permission entries found in .claude/settings.json"
        expected_behavior: "All permission entries in .claude/settings.json permissions.allow should be unique"

  claude_mcp_permissions:
    description: "MCP servers missing from Claude Code settings permissions"
    scope: project_level
    context: "All MCP servers defined in .mcp.json must have corresponding MCP() permission entries in .claude/settings.json. Missing permissions prevent MCP servers from being used."
    requires_project_context: true
    phases:
      - name: check_mcp_permissions
        type: claude_mcp_permissions
        failure_message: "MCP servers missing from .claude/settings.json permissions.allow array"
        expected_behavior: "Every MCP server in .mcp.json should have a corresponding MCP(server-name) entry in .claude/settings.json"
